Middlewares
CFP-DEV/RL-Server pull request #1
Opened 2018-09-14 07:37 UTC by young-6

2018-09-17 16:09 UTC, ghost requested changes

2018-09-17 16:09 UTC, Woddell commented on config/passport.js
> +      console.log(jwt_payload);
Why are you logging this? Is it for debugging or is there a purpose?

2018-09-17 16:09 UTC, Woddell commented on config/passport.js
> +        .catch(err => console.log(err));
shouldn't we have some error handling rather than just logging the error to the console?

2018-09-18 07:23 UTC, CFP-DEV commented
@young-6 When you apply changes & push them, then somewhere on this page should be button "resolve". Click it so I will be able to merge it with master branch.

2018-09-26 20:45 UTC, ghost approved these changes

2018-09-28 12:35 UTC, merged